/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary': '#00160e',
        'on-primary': '#ffffff',
        'primary-container': '#002d20',
        'on-primary-container': '#00a17a',
        'primary-fixed': '#6afbca',
        'primary-fixed-dim': '#48deaf',
        'on-primary-fixed': '#002116',
        'on-primary-fixed-variant': '#00513c',
        'secondary': '#406370',
        'on-secondary': '#ffffff',
        'secondary-container': '#c0e6f4',
        'on-secondary-container': '#446874',
        'secondary-fixed': '#c3e8f7',
        'secondary-fixed-dim': '#a7ccda',
        'on-secondary-fixed': '#001f28',
        'on-secondary-fixed-variant': '#274c57',
        'tertiary': '#00151a',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#002b34',
        'on-tertiary-container': '#6894a1',
        'tertiary-fixed': '#bceaf8',
        'tertiary-fixed-dim': '#a0cedb',
        'on-tertiary-fixed': '#001f26',
        'on-tertiary-fixed-variant': '#1e4d58',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'surface': '#f6fafd',
        'on-surface': '#171c1e',
        'surface-dim': '#d6dbdd',
        'surface-bright': '#f6fafd',
        'surface-variant': '#dfe3e6',
        'on-surface-variant': '#41484b',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f4f7',
        'surface-container': '#eaeef1',
        'surface-container-high': '#e4e9eb',
        'surface-container-highest': '#dfe3e6',
        'surface-tint': '#006c51',
        'outline': '#71787b',
        'outline-variant': '#c1c7cb',
        'inverse-surface': '#2c3133',
        'inverse-on-surface': '#edf1f4',
        'inverse-primary': '#48deaf',
        'background': '#f6fafd',
        'on-background': '#171c1e',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
